# This configuration file is intended to be modified for production
# purposes and is protected from subsequent updating by:
# git update-index --assume-unchanged /path/to/application.yml
# Use --no-assume-unchanged should subsequent changes need tracking.

defaults: &defaults
  sql_server_host:     192.168.1.23
  sql_server_port:     1433          # default = 1433
  sql_server_db:       EXO_UCB_TEST 
  sql_server_login:    username
  sql_server_password: cGFzc3dvcmQ=  # use db/utilities/encode.rb password
  sql_server_timeout:  1             # default = 1 (sec)
  ldap_host:           ballarat_thm
  ldap_port:           389           # default = 389
  ldap_base:           dc=ballarat_thm
  ldap_login:          query
  ldap_password:       cGFzc3dvcmQ=  # use db/utilities/encode.rb password
  ldap_enabled:        true
  order_watermark: 
  pops_host:           localhost:3000   
  tbr_root:            /tmp/tbr
  tbr_log:             /tmp/tbr
    
development:
  <<: *defaults
  ldap_enabled:        false
  exo_disabled:        true
  order_watermark:     '* Test Only *'
  
test:  # Don't change these because the test suite needs them
  <<: *defaults
  sql_server_host:     invalid
  sql_server_port:     1432
  sql_server_login:    username
  sql_server_password: cGFzc3dvcmQ=
  sql_server_timeout:  2
  ldap_host:           invalid
  ldap_port:           388
  ldap_login:          query
  ldap_password:       cGFzc3dvcmQ=
  ldap_enabled:        false
  
production:
  <<: *defaults
  sql_server_db:       EXO_UCB
  pops_host:           intranet.ucare.org.au/pops
  